2024-12-16 14:53:34,296 | INFO | "test_challenge" выполнен успешно
2024-12-16 14:53:34,296 | WARNING | Неверный тип данных для объекта Runner
Имя может быть только строкой, передано int
2024-12-16 14:53:34,297 | WARNING | Traceback (most recent call last):
  File "C:\Users\user\Documents\Python\test\git_test\tests_12_4.py", line 84, in test_run
    runner = Runner(2)
             ^^^^^^^^^
  File "C:\Users\user\Documents\Python\test\git_test\tests_12_4.py", line 16, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2024-12-16 14:53:34,297 | WARNING | Неверная скорость для Runner
Скорость не может быть отрицательной, сейчас -5
2024-12-16 14:53:34,299 | WARNING | Traceback (most recent call last):
  File "C:\Users\user\Documents\Python\test\git_test\tests_12_4.py", line 73, in test_walk
    runner = Runner("Вася", -5)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\Python\test\git_test\tests_12_4.py", line 21, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

